# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import thesocialnetwork.models


class Migration(migrations.Migration):

    dependencies = [
        ('thesocialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=thesocialnetwork.models.get_image_path),
        ),
    ]
