# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesocialnetwork', '0002_auto_20180119_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriendShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_id', models.IntegerField()),
                ('to_user_id', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
            ],
        ),
    ]
