# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesocialnetwork', '0004_userfriendship_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfriendship',
            name='from_user_id',
        ),
        migrations.RemoveField(
            model_name='userfriendship',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='userfriendship',
            name='to_user_id',
        ),
        migrations.AddField(
            model_name='userfriendship',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfriendship',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
