# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesocialnetwork', '0005_auto_20180125_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendship',
            name='time_of_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 11, 19, 23, 105271)),
            preserve_default=False,
        ),
    ]
