# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 06:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('thesocialnetwork', '0007_auto_20180126_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 6, 53, 8, 654507)),
            preserve_default=False,
        ),
    ]
