# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesocialnetwork', '0008_auto_20180127_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
